package domain.constraints;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.interfaces.Constrainable;
import domain.interfaces.Constrainer;
import java.io.Serializable;
import javax.persistence.*;

/**
 * Constraint generated by hbm2java
 */
@Entity
@MappedSuperclass
public abstract class Constraint implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CS_SEQUENCE")
    @SequenceGenerator(name = "CS_SEQUENCE")
    protected Long id;
    // private ConstraintType type;
    protected Long constrainer;
    protected Long constrained;

    protected Constraint() {
    }

    protected Constraint(Constrainer constrainer, Constrainable constrained) {
        this.constrainer = constrainer.getId();
        this.constrained = constrained.getId();
    }
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Key getKey() {
        return key;
    }
 
    public Long getConstrainer() {
        return this.constrainer;
    }

    public void setConstrainer(Constrainer constrainer) {
        this.constrainer = constrainer.getId();
    }

    public Long getConstrained() {
        return this.constrained;
    }

    public void setConstrained(Constrainable constrained) {
        this.constrained = constrained.getId();
    }
}
