package domain.constraints;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import java.io.Serializable;
import javax.persistence.*;

/**
 * Constraint generated by hbm2java
 */
@Entity
@MappedSuperclass
public abstract class Constraint implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CS_SEQUENCE")
    @SequenceGenerator(name = "CS_SEQUENCE")
    protected Long id;
    // private ConstraintType type;
    protected Key constrainer;
    protected Key constrained;

    protected Constraint() {
    }

    protected Constraint(Key constrainer, Key constrained) {
        this.constrainer = constrainer;
        this.constrained = constrained;
    }
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Key getKey() {
        return key;
    }
 
    protected Key getConstrainer() {
        return this.constrainer;
    }

    protected void setConstrainer(Key constrainer) {
        this.constrainer = constrainer;
    }

    protected Key getConstrained() {
        return this.constrained;
    }

    protected void setConstrained(Key constrained) {
        this.constrained = constrained;
    }
}
