package domain;
// Generated 18-feb-2012 18:51:31 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.enums.AanvraagStatus;
import domain.enums.AanvraagType;
import domain.interfaces.Trackable;
import java.util.Date;
import javax.persistence.*;

/**
 * Aanvraag generated by hbm2java
 */
@Entity
public class Aanvraag implements java.io.Serializable, Trackable {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Key key;
    @Basic(optional=false)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="A_SEQUENCE")
    @SequenceGenerator(name="A_SEQUENCE")
    private Long id;
    @ManyToOne
    private Gebruiker eigenaar;
    private AanvraagType type;
    private AanvraagStatus status;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date aanmaakDatum;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(nullable=true)
    private Date afwerkDatum;
    private String commentaar;
    private Integer veld;
    private String correctieWaarde;
    // TODO make this is a list
    private String bestemmelingen;

    public Aanvraag() {
    }

    public Aanvraag(Gebruiker eigenaar, AanvraagType type, AanvraagStatus status, Date aanmaakDatum, String bestemmelingen) {
        this.eigenaar = eigenaar;
        this.type = type;
        this.status = status;
        this.aanmaakDatum = aanmaakDatum;
        this.bestemmelingen = bestemmelingen;
    }

    public Aanvraag(Gebruiker eigenaar, AanvraagType type, AanvraagStatus status, Date aanmaakDatum, Date afwerkDatum, String commentaar, Integer veld, String correctieWaarde, String bestemmelingen) {
        this.eigenaar = eigenaar;
        this.type = type;
        this.status = status;
        this.aanmaakDatum = aanmaakDatum;
        this.afwerkDatum = afwerkDatum;
        this.commentaar = commentaar;
        this.veld = veld;
        this.correctieWaarde = correctieWaarde;
        this.bestemmelingen = bestemmelingen;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Gebruiker getEigenaar() {
        return this.eigenaar;
    }

    public void setEigenaar(Gebruiker eigenaar) {
        this.eigenaar = eigenaar;
    }

    public AanvraagType getType() {
        return this.type;
    }

    public void setType(AanvraagType type) {
        this.type = type;
    }

    public AanvraagStatus getStatus() {
        return this.status;
    }

    public void setStatus(AanvraagStatus status) {
        this.status = status;
    }

    public Date getAanmaakDatum() {
        return this.aanmaakDatum;
    }

    public void setAanmaakDatum(Date aanmaakDatum) {
        this.aanmaakDatum = aanmaakDatum;
    }

    public Date getAfwerkDatum() {
        return this.afwerkDatum;
    }

    public void setAfwerkDatum(Date afwerkDatum) {
        this.afwerkDatum = afwerkDatum;
    }

    public String getCommentaar() {
        return this.commentaar;
    }

    public void setCommentaar(String commentaar) {
        this.commentaar = commentaar;
    }

    public Integer getVeld() {
        return this.veld;
    }

    public void setVeld(Integer veld) {
        this.veld = veld;
    }

    public String getCorrectieWaarde() {
        return this.correctieWaarde;
    }

    public void setCorrectieWaarde(String correctieWaarde) {
        this.correctieWaarde = correctieWaarde;
    }

    public String getBestemmelingen() {
        return this.bestemmelingen;
    }

    public void setBestemmelingen(String bestemmelingen) {
        this.bestemmelingen = bestemmelingen;
    }

    @Override
    public String toString() {
        return "AANVRAAG: [" + id + "]";
    }
    
    
}
