package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import domain.enums.Operator;

/**
 * Conditie generated by hbm2java
 */
public class Conditie implements java.io.Serializable {

    private Integer id;
    private Conditie rechter;
    private Conditie linker;
    private String naam;
    private String commentaar;
    private Operator operator;
    private String expressie;

    public Conditie() {
    }

    public Conditie(String naam) {
        this.naam = naam;
    }

    public Conditie(Conditie linker, Conditie rechter, String naam, String commentaar, Operator operator, String expressie) {
        this.linker = linker;
        this.rechter = rechter;
        this.naam = naam;
        this.commentaar = commentaar;
        this.operator = operator;
        this.expressie = expressie;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Conditie getRechter() {
        return this.rechter;
    }

    public void setRechter(Conditie rechter) {
        this.rechter = rechter;
    }

    public Conditie getLinker() {
        return this.linker;
    }

    public void setLinker(Conditie linker) {
        this.linker = linker;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public String getCommentaar() {
        return this.commentaar;
    }

    public void setCommentaar(String commentaar) {
        this.commentaar = commentaar;
    }

    public Operator getOperator() {
        return this.operator;
    }

    public void setOperator(Operator operator) {
        this.operator = operator;
    }

    public String getExpressie() {
        return this.expressie;
    }

    public void setExpressie(String expressie) {
        this.expressie = expressie;
    }
}
