package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import domain.enums.ConstraintType;
import domain.interfaces.Constrainable;
import domain.interfaces.Constrainer;

/**
 * Constraint generated by hbm2java
 */
public class Constraint implements java.io.Serializable {

    private Integer id;
    private ConstraintType type;
    private Constrainer constrainer;
    private Constrainable constrained;
    private boolean standaard;
    private boolean wederkerig;

    public Constraint() {
    }

    public Constraint(ConstraintType type, Constrainer constrainer, Constrainable constrained) {
        this.type = type;
        this.constrainer = constrainer;
        this.constrained = constrained;
    }

    public Constraint(ConstraintType type, Constrainer constrainer, Constrainable constrained, boolean standaard, boolean wederkerig) {
        this.type = type;
        this.constrainer = constrainer;
        this.constrained = constrained;
        this.standaard = standaard;
        this.wederkerig = wederkerig;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ConstraintType getType() {
        return this.type;
    }

    public void setType(ConstraintType type) {
        this.type = type;
    }

    public Constrainer getConstrainer() {
        return this.constrainer;
    }

    public void setConstrainer(Constrainer constrainer) {
        this.constrainer = constrainer;
    }

    public Constrainable getConstrained() {
        return this.constrained;
    }

    public void setConstrained(Constrainable constrained) {
        this.constrained = constrained;
    }

    public boolean isStandaard() {
        return this.standaard;
    }

    public void setStandaard(boolean standaard) {
        this.standaard = standaard;
    }

    public boolean isWederkerig() {
        return wederkerig;
    }

    public void setWederkerig(boolean wederkerig) {
        this.wederkerig = wederkerig;
    }
}
