package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import java.util.List;
import javax.persistence.*;

/**
 * Doelgroep generated by hbm2java
 */
public class Doelgroep implements java.io.Serializable {

    private Key key;
    private Long id;
    private String naam;
    private Integer graad;
    private List<DoelgroepLeerling> leerlingen;

    public Doelgroep() {
    }

    public Doelgroep(String naam) {
        this.naam = naam;
    }

    public Doelgroep(String naam, Integer graad) {
        this.naam = naam;
        this.graad = graad;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public Integer getGraad() {
        return this.graad;
    }

    public void setGraad(Integer graad) {
        this.graad = graad;
    }

    public List<DoelgroepLeerling> getLeerlingen() {
        return leerlingen;
    }

    public void setLeerlingen(List<DoelgroepLeerling> leerlingen) {
        this.leerlingen = leerlingen;
    }

    public void addLeerling(int jaar, String groep, Leerling leerling) {
        leerlingen.add(new DoelgroepLeerling(leerling, this, groep, jaar));
    }

    // TODO move to database class
//    public Map<String, Integer> getAantallenPerGroep() {
//        Map<String, Integer> aantallen = new HashMap<String, Integer>();
//
//        for (Object oGroep : leerlingen.keySet()) {
//            String groep = (String) oGroep;
//            int groepAtl = 0;
//            List<Leerling> lln = (List<Leerling>) leerlingen.get(oGroep);
//            for (Leerling l : lln) {
//                Calendar calStart = new GregorianCalendar();
//                calStart.setTime(l.getStartDatum());
//                int startYear = calStart.get(Calendar.YEAR);
//                int startMonth = calStart.get(Calendar.MONTH) + 1;
//                // startdatum ligt voor schooljaar
//                // of startdatum ligt in schooljaar maar nog steeds in dat schooljaar
//                if (startYear < GlobalValues.HUIDIG_SCHOOLJAAR
//                        || (startYear == GlobalValues.HUIDIG_SCHOOLJAAR && startMonth >= 9)
//                        || (startYear == GlobalValues.HUIDIG_SCHOOLJAAR + 1 && startMonth < 9)) {
//                    if (l.getEindDatum() != null) {
//                        Calendar calEnd = new GregorianCalendar();
//                        calEnd.setTime(l.getEindDatum());
//                        int endYear = calStart.get(Calendar.YEAR);
//                        int endMonth = calStart.get(Calendar.MONTH) + 1;
//                        // einddatum ligt na schooljaar
//                        // of einddatum ligt schooljaar maar nog steeds in dat schooljaar
//                        if (endYear > GlobalValues.HUIDIG_SCHOOLJAAR + 1
//                                || (endYear == GlobalValues.HUIDIG_SCHOOLJAAR && endMonth >= 9)
//                                || (endYear == GlobalValues.HUIDIG_SCHOOLJAAR + 1 && endMonth < 9)) {
//                            groepAtl++;
//                        }
//                    } else {
//                        groepAtl++;
//                    }
//
//
//                }
//            }
//            aantallen.put(groep, groepAtl);
//        }
//
//        return aantallen;
//    }
}
