package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;

/**
 * Doelgroep generated by hbm2java
 */
@Entity
public class Doelgroep implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Key key;
    @Basic(optional=false)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="D_SEQUENCE")
    @SequenceGenerator(name="D_SEQUENCE")
    private Long id;
    private String naam;
    private Integer graad;
    @OneToMany(mappedBy = "doelgroep")
    @Basic
    private List<SchooljaarGroep> groepen = new ArrayList<SchooljaarGroep>();

    public Doelgroep() {
    }

    public Doelgroep(String naam) {
        this.naam = naam;
    }

    public Key getKey() {
        return key;
    }

    public Doelgroep(String naam, Integer graad) {
        this.naam = naam;
        this.graad = graad;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public Integer getGraad() {
        return this.graad;
    }

    public void setGraad(Integer graad) {
        this.graad = graad;
    }

    public List<SchooljaarGroep> getGroepen() {
        return groepen;
    }

    public void setGroepen(List<SchooljaarGroep> groepen) {
        this.groepen = groepen;
    }

    public void addLeerling(int jaar, String groep, Leerling leerling) {
        boolean done = false;
        for (SchooljaarGroep sg : groepen) {
            if (sg.getGroep().equals(groep) && sg.getSchooljaar() == jaar) {
                sg.addLeerling(leerling);
                done = true;
            }
        }
        
        if (!done) {
            SchooljaarGroep sg = new SchooljaarGroep(this, groep, jaar);
            sg.addLeerling(leerling);
            groepen.add(sg);
        }
    }
    
    @Override
    public String toString() {
        return "DOELGROEP [" + id + ", " + graad + ", " + naam + ", " + groepen.size() + "]";
    }

    // TODO move to database class
//    public Map<String, Integer> getAantallenPerGroep() {
//        Map<String, Integer> aantallen = new HashMap<String, Integer>();
//
//        for (Object oGroep : leerlingen.keySet()) {
//            String groep = (String) oGroep;
//            int groepAtl = 0;
//            List<Leerling> lln = (List<Leerling>) leerlingen.get(oGroep);
//            for (Leerling l : lln) {
//                Calendar calStart = new GregorianCalendar();
//                calStart.setTime(l.getStartDatum());
//                int startYear = calStart.get(Calendar.YEAR);
//                int startMonth = calStart.get(Calendar.MONTH) + 1;
//                // startdatum ligt voor schooljaar
//                // of startdatum ligt in schooljaar maar nog steeds in dat schooljaar
//                if (startYear < GlobalValues.HUIDIG_SCHOOLJAAR
//                        || (startYear == GlobalValues.HUIDIG_SCHOOLJAAR && startMonth >= 9)
//                        || (startYear == GlobalValues.HUIDIG_SCHOOLJAAR + 1 && startMonth < 9)) {
//                    if (l.getEindDatum() != null) {
//                        Calendar calEnd = new GregorianCalendar();
//                        calEnd.setTime(l.getEindDatum());
//                        int endYear = calStart.get(Calendar.YEAR);
//                        int endMonth = calStart.get(Calendar.MONTH) + 1;
//                        // einddatum ligt na schooljaar
//                        // of einddatum ligt schooljaar maar nog steeds in dat schooljaar
//                        if (endYear > GlobalValues.HUIDIG_SCHOOLJAAR + 1
//                                || (endYear == GlobalValues.HUIDIG_SCHOOLJAAR && endMonth >= 9)
//                                || (endYear == GlobalValues.HUIDIG_SCHOOLJAAR + 1 && endMonth < 9)) {
//                            groepAtl++;
//                        }
//                    } else {
//                        groepAtl++;
//                    }
//
//
//                }
//            }
//            aantallen.put(groep, groepAtl);
//        }
//
//        return aantallen;
//    }
}
