package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import javax.persistence.*;



/**
 * Doelgroep generated by hbm2java
 */
public class DoelgroepLeerling implements java.io.Serializable {
    private Key key;
    private Leerling leerling;
    private Doelgroep doelgroep;
    private String groep;
    private int schooljaar;

    public DoelgroepLeerling() {
    }

    public DoelgroepLeerling(Leerling leerling, Doelgroep doelgroep, String groep, int schooljaar) {
        this.leerling = leerling;
        this.doelgroep = doelgroep;
        this.groep = groep;
        this.schooljaar = schooljaar;
    }

    public Doelgroep getDoelgroep() {
        return doelgroep;
    }

    public String getGroep() {
        return groep;
    }

    public int getSchooljaar() {
        return schooljaar;
    }

    public Leerling getLeerling() {
        return leerling;
    }

    public void setDoelgroep(Doelgroep doelgroep) {
        this.doelgroep = doelgroep;
    }

    public void setGroep(String groep) {
        this.groep = groep;
    }

    public void setLeerling(Leerling leerling) {
        this.leerling = leerling;
    }

    public void setSchooljaar(int schooljaar) {
        this.schooljaar = schooljaar;
    }

    
}
