package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.interfaces.Constrained;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * GebruikerType generated by hbm2java
 */
@Entity
public class GebruikerType implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY, generator="keyGenerator")
    private Key key;
    @Basic(optional=false)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="GT_SEQUENCE")
    @SequenceGenerator(initialValue=11000000, name="GT_SEQUENCE")
    private Long id;
    @Basic(optional=false)
    private String naam;
    @Basic(optional=false)
    private boolean standaard;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Basic(optional=false)
    private Date creationDate;
    @Basic
    private List<Long> rechten = new ArrayList<Long>();
    @OneToMany(mappedBy = "gebruikerType", cascade= CascadeType.ALL)
    @Basic
    private List<Gebruiker> gebruikers = new ArrayList<Gebruiker>();

    public GebruikerType() {
    }

    public GebruikerType(String naam, boolean standaard) {
        this.naam = naam;
        this.standaard = standaard;
        this.creationDate = new Date(System.currentTimeMillis());
    }

    public GebruikerType(String naam, boolean standaard, List<Gebruiker> gebruikers) {
        this.naam = naam;
        this.standaard = standaard;
        this.creationDate = new Date(System.currentTimeMillis());
        this.gebruikers = gebruikers;
    }

    public Date getCreationDate() {
        return creationDate;
    }
    
    public Long getId() {
        return this.id;
    }

    public Key getKey() {
        return key;
    }

    public void setKey(Key key) {
        this.key = key;
    }
    
    

    public void setId(Long id) {
        this.id = id;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public boolean isStandaard() {
        return this.standaard;
    }

    public void setStandaard(boolean standaard) {
        this.standaard = standaard;
    }

    public List<Gebruiker> getGebruikers() {
        return this.gebruikers;
    }

    public void setGebruikers(List<Gebruiker> gebruikers) {
        this.gebruikers = gebruikers;
    }
    
    public void add(Gebruiker gebruiker) {
        if (gebruikers == null) {
            gebruikers = new ArrayList<Gebruiker>();
        }
        
        gebruikers.add(gebruiker);
    }

    public List<Long> getRechten() {
        return rechten;
    }

    public void setRechten(List<Long> rechten) {
        this.rechten = rechten;
    }
    
    public void addRecht(Constrained recht) {
        rechten.add(recht.getId());
    }

    @Override
    public String toString() {
        return "GEBRUIKERTYPE [" + id + ", " + naam + ", " + standaard + ", " + gebruikers.size() + "]";
    }

    
    
}
