package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.enums.InputVeldType;
import domain.interfaces.Constrained;
import javax.persistence.*;

/**
 * InputVeld generated by hbm2java
 */
@Entity
public class InputVeld implements java.io.Serializable, Constrained {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Key key;
    @Basic(optional=false)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="IV_SEQUENCE")
    @SequenceGenerator(name="IV_SEQUENCE")
    private Long id;
    private String naam;
    private InputVeldType type;
    private Integer minimum;
    private Integer maximum;

    public InputVeld() {
    }

    public InputVeld(String naam, InputVeldType type) {
        this.naam = naam;
        this.type = type;
    }

    public InputVeld(String naam, InputVeldType type, Integer minimum, Integer maximum) {
        this.naam = naam;
        this.type = type;
        this.minimum = minimum;
        this.maximum = maximum;
    }
    
    

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public InputVeldType getType() {
        return this.type;
    }

    public void setType(InputVeldType type) {
        this.type = type;
    }

    public Integer getMax() {
        return maximum;
    }

    public Integer getMin() {
        return minimum;
    }

    public void setMax(Integer max) {
        this.maximum = max;
    }

    public void setMin(Integer min) {
        this.minimum = min;
    }

    @Override
    public String toString() {
        return "INPUTVELD: [" + id + ", " + naam + ", " + type + ", " + minimum + ", " + maximum + "]";
    }

    
}
