package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import javax.persistence.*;


/**
 * InputWaarde generated by hbm2java
 */
@Entity
public class InputWaarde implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Key key;
    
    private Key inputVeld;
    @ManyToOne
    private Opdracht opdracht;
    private String waarde;

    public InputWaarde() {
    }

    public InputWaarde(InputVeld inputveld, Opdracht opdracht, String waarde) {
        this.inputVeld = inputveld.getKey();
        this.opdracht = opdracht;
        this.waarde = waarde;
    }

    public Key getInputVeld() {
        return this.inputVeld;
    }

    public void setInputVeld(InputVeld inputVeld) {
        this.inputVeld = inputVeld.getKey();
    }

    public Opdracht getOpdracht() {
        return this.opdracht;
    }

    public void setOpdracht(Opdracht opdracht) {
        this.opdracht = opdracht;
    }

    public String getWaarde() {
        return this.waarde;
    }

    public void setWaarde(String waarde) {
        this.waarde = waarde;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj != null) {
            if (obj instanceof InputWaarde) {
                InputWaarde input = (InputWaarde) obj;
                boolean veld = false;
                boolean opdr = false;
                if (input.getInputVeld() != null) {
                    veld = input.getInputVeld().equals(inputVeld);
                }

                if (input.getOpdracht() != null) {
                    opdr = input.getOpdracht().equals(opdracht);
                }
                return veld && opdr;
            }
            return obj.hashCode() == this.hashCode();
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + (this.inputVeld != null ? this.inputVeld.hashCode() : 0);
        hash = 17 * hash + (this.opdracht != null ? this.opdracht.hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "INPUTWAARDE [" + inputVeld + ", " + opdracht + ", " + waarde + "]";
    }
}
