package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import domain.enums.Locatie;
import domain.enums.Selectie;
import domain.enums.Weergave;
import domain.enums.Zichtbaarheid;

/**
 * LayoutProperty generated by hbm2java
 */
public class LayoutProperty implements java.io.Serializable {

    private OptieType optieType;
    private Gebruiker gebruiker;
    private Zichtbaarheid zichtbaar;
    private Locatie locatie;
    private Selectie selectie;
    private Weergave weergave;

    public LayoutProperty() {
    }

    public LayoutProperty(OptieType optieType, Gebruiker gebruiker, Zichtbaarheid zichtbaar, Locatie locatie, Selectie selectie, Weergave weergave) {
        this.optieType = optieType;
        this.gebruiker = gebruiker;
        this.zichtbaar = zichtbaar;
        this.locatie = locatie;
        this.selectie = selectie;
        this.weergave = weergave;
    }

    public OptieType getOptieType() {
        return this.optieType;
    }

    public void setOptieType(OptieType optieType) {
        this.optieType = optieType;
    }

    public Gebruiker getGebruiker() {
        return this.gebruiker;
    }

    public void setGebruiker(Gebruiker gebruiker) {
        this.gebruiker = gebruiker;
    }

    public Zichtbaarheid getZichtbaar() {
        return this.zichtbaar;
    }

    public void setZichtbaar(Zichtbaarheid zichtbaar) {
        this.zichtbaar = zichtbaar;
    }

    public Locatie getLocatie() {
        return this.locatie;
    }

    public void setLocatie(Locatie locatie) {
        this.locatie = locatie;
    }

    public Selectie getSelectie() {
        return this.selectie;
    }

    public void setSelectie(Selectie selectie) {
        this.selectie = selectie;
    }

    public Weergave getWeergave() {
        return this.weergave;
    }

    public void setWeergave(Weergave weergave) {
        this.weergave = weergave;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + (this.optieType != null ? this.optieType.hashCode() : 0);
        hash = 71 * hash + (this.gebruiker != null ? this.gebruiker.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj != null) {
            if (obj instanceof LayoutProperty) {
                LayoutProperty input = (LayoutProperty) obj;
                boolean gebr = false;
                boolean optt = false;
                if (input.getGebruiker() != null) {
                    gebr = input.getGebruiker().equals(gebruiker);
                }
                if (input.getOptieType() != null) {
                    optt = input.getOptieType().equals(optieType);
                }
                return optt && gebr;
            }
            return obj.hashCode() == this.hashCode();
        }
        return false;
    }
}
