package domain;
// Generated 18-feb-2012 18:51:31 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.interfaces.Trackable;
import java.util.Date;
import javax.persistence.*;

/**
 * Melding generated by hbm2java
 */
public class Melding implements java.io.Serializable {
    private Key key;
    private Gebruiker gebruiker;
    private Trackable volgt;
    private Date gewijzigd;
    private boolean email;

    public Melding() {
    }

    public Melding(Trackable volgt, Gebruiker gebruiker, Date gewijzigd, boolean email) {
        this.gebruiker = gebruiker;
        this.gewijzigd = gewijzigd;
        this.email = email;
        this.volgt = volgt;
    }

    public Trackable getVolgt() {
        return volgt;
    }

    public void setVolgt(Trackable volgt) {
        this.volgt = volgt;
    }

    public Gebruiker getGebruiker() {
        return this.gebruiker;
    }

    public void setGebruiker(Gebruiker gebruiker) {
        this.gebruiker = gebruiker;
    }

    public Date getGewijzigd() {
        return this.gewijzigd;
    }

    public void setGewijzigd(Date gewijzigd) {
        this.gewijzigd = gewijzigd;
    }

    public boolean isEmail() {
        return this.email;
    }

    public void setEmail(boolean email) {
        this.email = email;
    }
}
