package domain;
// Generated 18-feb-2012 18:51:31 by Hibernate Tools 3.2.1.GA

/**
 * OpdrachtTypeInput generated by hbm2java
 */
public class OpdrachtTypeInput implements java.io.Serializable {

    private int inputVeldInt;
    private int opdrachtTypeInt;
    private InputVeld inputVeld;
    private OpdrachtType opdrachtType;
    private boolean verplicht;
    private boolean wijzigbaar;
    private boolean zichtbaar;
    private int volgorde;

    public int getInputVeldInt() {
        return inputVeldInt;
    }

    public void setInputVeldInt(int inputVeldInt) {
        this.inputVeldInt = inputVeldInt;
    }

    public int getOpdrachtTypeInt() {
        return opdrachtTypeInt;
    }

    public void setOpdrachtTypeInt(int opdrachtTypeInt) {
        this.opdrachtTypeInt = opdrachtTypeInt;
    }

    public OpdrachtTypeInput() {
    }

    public OpdrachtTypeInput(InputVeld inputVeld, OpdrachtType opdrachtType, boolean verplicht, boolean wijzigbaar, boolean zichtbaar, int volgorde) {
        this.inputVeld = inputVeld;
        this.opdrachtType = opdrachtType;
        this.verplicht = verplicht;
        this.wijzigbaar = wijzigbaar;
        this.zichtbaar = zichtbaar;
        this.volgorde = volgorde;
    }

    public InputVeld getInputVeld() {
        return this.inputVeld;
    }

    public void setInputVeld(InputVeld inputVeld) {
        this.inputVeld = inputVeld;
    }

    public OpdrachtType getOpdrachtType() {
        return this.opdrachtType;
    }

    public void setOpdrachtType(OpdrachtType opdrachtType) {
        this.opdrachtType = opdrachtType;
    }

    public boolean isVerplicht() {
        return this.verplicht;
    }

    public void setVerplicht(boolean verplicht) {
        this.verplicht = verplicht;
    }

    public boolean isWijzigbaar() {
        return this.wijzigbaar;
    }

    public void setWijzigbaar(boolean wijzigbaar) {
        this.wijzigbaar = wijzigbaar;
    }

    public boolean isZichtbaar() {
        return this.zichtbaar;
    }

    public void setZichtbaar(boolean zichtbaar) {
        this.zichtbaar = zichtbaar;
    }

    public int getVolgorde() {
        return this.volgorde;
    }

    public void setVolgorde(int volgorde) {
        this.volgorde = volgorde;
    }
}
