package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import domain.enums.OpdrachtStatus;
import domain.interfaces.Constrained;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Opdracht generated by hbm2java
 */
@Entity
public class Opdracht implements java.io.Serializable, Constrained {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;
    private Gebruiker opdrachtgever;
    private Gebruiker uitvoerder;
    private OpdrachtType opdrachtType;
    private String bestand;
    private int aantal;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date aanmaakDatum;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date printDatum;
    private OpdrachtStatus status;
    private String commentaar;
    private Set<InputWaarde> inputWaarden = new HashSet<InputWaarde>(0);
    private Set<Doelgroep> doelgroepen = new HashSet<Doelgroep>(0);
    private Set<Optie> opties = new HashSet<Optie>(0);

    public Opdracht() {
    }

    public Opdracht(Gebruiker opdrachtgever, OpdrachtType opdrachtType, String bestand, int aantal, Date aanmaakDatum, OpdrachtStatus status) {
        this.opdrachtgever = opdrachtgever;
        this.opdrachtType = opdrachtType;
        this.bestand = bestand;
        this.aantal = aantal;
        this.aanmaakDatum = aanmaakDatum;
        this.status = status;
    }

    public Opdracht(Gebruiker opdrachtgever, Gebruiker uitvoerder, OpdrachtType opdrachtType, String bestand, int aantal, Date aanmaakDatum, Date printDatum, OpdrachtStatus status, String commentaar, Set<InputWaarde> inputWaarden, Set<Doelgroep> doelgroepen, Set<Optie> opties) {
        this.opdrachtgever = opdrachtgever;
        this.uitvoerder = uitvoerder;
        this.opdrachtType = opdrachtType;
        this.bestand = bestand;
        this.aantal = aantal;
        this.aanmaakDatum = aanmaakDatum;
        this.printDatum = printDatum;
        this.status = status;
        this.commentaar = commentaar;
        this.inputWaarden = inputWaarden;
        this.doelgroepen = doelgroepen;
        this.opties = opties;
    }

    public InputWaarde addInputWaarde(InputVeld veld, String waarde) {
        InputWaarde present = getInputWaardeFor(veld);
        if (present == null) {
            InputWaarde input = new InputWaarde(veld, this, waarde);
            inputWaarden.add(input);
            present = input;
        } else {
            present.setWaarde(waarde);
        }
        return present;
    }

    public void addDoelgroep(Doelgroep doelgroep) {
        doelgroepen.add(doelgroep);
    }

    public void addOptie(Optie optie) {
        opties.add(optie);
    }

    public InputWaarde getInputWaardeFor(InputVeld veld) {
        for (InputWaarde waarde : inputWaarden) {
            if (waarde.getInputVeld().equals(veld)) {
                return waarde;
            }
        }
        return null;
    }
    
    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Gebruiker getOpdrachtgever() {
        return this.opdrachtgever;
    }

    public void setOpdrachtgever(Gebruiker opdrachtgever) {
        this.opdrachtgever = opdrachtgever;
    }

    public Gebruiker getUitvoerder() {
        return uitvoerder;
    }

    public void setUitvoerder(Gebruiker uitvoerder) {
        this.uitvoerder = uitvoerder;
    }

    public OpdrachtType getOpdrachtType() {
        return this.opdrachtType;
    }

    public void setOpdrachtType(OpdrachtType opdrachtType) {
        this.opdrachtType = opdrachtType;
    }

    public String getBestand() {
        return this.bestand;
    }

    public void setBestand(String bestand) {
        this.bestand = bestand;
    }

    public int getAantal() {
        return this.aantal;
    }

    public void setAantal(int aantal) {
        this.aantal = aantal;
    }

    public Date getAanmaakDatum() {
        return this.aanmaakDatum;
    }

    public void setAanmaakDatum(Date aanmaakDatum) {
        this.aanmaakDatum = aanmaakDatum;
    }

    public Date getPrintDatum() {
        return this.printDatum;
    }

    public void setPrintDatum(Date printDatum) {
        this.printDatum = printDatum;
    }

    public OpdrachtStatus getStatus() {
        return this.status;
    }

    public void setStatus(OpdrachtStatus status) {
        this.status = status;
    }

    public String getCommentaar() {
        return this.commentaar;
    }

    public void setCommentaar(String commentaar) {
        this.commentaar = commentaar;
    }

    public Set<InputWaarde> getInputWaarden() {
        return this.inputWaarden;
    }

    public void setInputWaarden(Set<InputWaarde> inputWaarden) {
        this.inputWaarden = inputWaarden;
    }

    public Set<Doelgroep> getDoelgroepen() {
        return this.doelgroepen;
    }

    public void setDoelgroepen(Set<Doelgroep> doelgroepen) {
        this.doelgroepen = doelgroepen;
    }

    public Set<Optie> getOpties() {
        return this.opties;
    }

    public void setOpties(Set<Optie> opties) {
        this.opties = opties;
    }

    @Override
    public String toString() {
        return "TEST: " + id;
    }

    
}
