package domain;
// Generated 18-feb-2012 18:51:31 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import database.InputVeldDB;
import javax.persistence.*;


/**
 * OpdrachtTypeInput generated by hbm2java
 */
@Entity
public class OpdrachtTypeInput implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Key key;
    private Key inputVeldKey;
    @ManyToOne
    private OpdrachtType opdrachtType;
    private boolean verplicht;
    private boolean wijzigbaar;
    private boolean zichtbaar;
    private int volgorde;

    public OpdrachtTypeInput() {
    }

    public OpdrachtTypeInput(InputVeld inputVeld, OpdrachtType opdrachtType, boolean verplicht, boolean wijzigbaar, boolean zichtbaar, int volgorde) {
        this.inputVeldKey = inputVeld.getKey();
        this.opdrachtType = opdrachtType;
        this.verplicht = verplicht;
        this.wijzigbaar = wijzigbaar;
        this.zichtbaar = zichtbaar;
        this.volgorde = volgorde;
    }

    public void setInputVeld(InputVeld inputVeld) {
        this.inputVeldKey = inputVeld.getKey();
    }

    public OpdrachtType getOpdrachtType() {
        return this.opdrachtType;
    }

    public void setOpdrachtType(OpdrachtType opdrachtType) {
        this.opdrachtType = opdrachtType;
    }

    public boolean isVerplicht() {
        return this.verplicht;
    }

    public void setVerplicht(boolean verplicht) {
        this.verplicht = verplicht;
    }

    public boolean isWijzigbaar() {
        return this.wijzigbaar;
    }

    public void setWijzigbaar(boolean wijzigbaar) {
        this.wijzigbaar = wijzigbaar;
    }

    public boolean isZichtbaar() {
        return this.zichtbaar;
    }

    public void setZichtbaar(boolean zichtbaar) {
        this.zichtbaar = zichtbaar;
    }

    public int getVolgorde() {
        return this.volgorde;
    }

    public void setVolgorde(int volgorde) {
        this.volgorde = volgorde;
    }

    public InputVeld getInputVeld() {
        InputVeldDB ivdb = new InputVeldDB();
        return ivdb.get(inputVeldKey);
    }
    
    @Override
    public String toString() {
        return "OPDRACHTTYPEINPUT [" + inputVeldKey + ", " + opdrachtType + ", " + verplicht + ", " + wijzigbaar + ", " + zichtbaar + ", " + volgorde + "]";
    }
    
    
}
