package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import domain.interfaces.Constrained;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * OpdrachtType generated by hbm2java
 */
@Entity
public class OpdrachtType implements java.io.Serializable, Constrained {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;
    private PrijsKlasse prijsKlasse;
    private String naam;
    private String omschrijving;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date van;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date tot;
    private Set<OpdrachtTypeInput> inputVelden = new HashSet<OpdrachtTypeInput>(0);
    private Set<OptieType> optieTypes = new HashSet<OptieType>(0);

    public OpdrachtType() {
    }

    public OpdrachtType(PrijsKlasse prijstypes, String naam, String omschrijving, Date van) {
        this.prijsKlasse = prijstypes;
        this.naam = naam;
        this.van = van;
        this.omschrijving = omschrijving;
    }

    public OpdrachtType(PrijsKlasse prijstypes, String naam, String omschrijving, 
            Date van, Date tot, Set<OpdrachtTypeInput> inputVelden, Set<OptieType> optieTypes) {
        this.prijsKlasse = prijstypes;
        this.naam = naam;
        this.van = van;
        this.tot = tot;
        this.inputVelden = inputVelden;
        this.optieTypes = optieTypes;
    }

    public Set<OptieType> getOptieTypes() {
        return optieTypes;
    }

    public void setOptieTypes(Set<OptieType> optieTypes) {
        this.optieTypes = optieTypes;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public PrijsKlasse getPrijsKlasse() {
        return this.prijsKlasse;
    }

    public void setPrijsKlasse(PrijsKlasse prijsKlasse) {
        this.prijsKlasse = prijsKlasse;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public String getOmschrijving() {
        return omschrijving;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    public Date getVan() {
        return this.van;
    }

    public void setVan(Date van) {
        this.van = van;
    }

    public Date getTot() {
        return this.tot;
    }

    public void setTot(Date tot) {
        this.tot = tot;
    }

    public Set<OpdrachtTypeInput> getInputVelden() {
        return this.inputVelden;
    }

    public void setInputVelden(Set<OpdrachtTypeInput> inputVelden) {
        this.inputVelden = inputVelden;
    }
}
