package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.enums.OptieStatus;
import domain.interfaces.Constrainable;
import domain.interfaces.Constrained;
import domain.interfaces.Constrainer;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * OptieType generated by hbm2java
 */
@Entity
public class OptieType implements java.io.Serializable, Constrainer, Constrainable, Constrained {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "OT_SEQUENCE")
    @SequenceGenerator(name = "OT_SEQUENCE")
    @Column(nullable=false)
    private Long id;
    private String naam;
    private String omschrijving;
    private int maximum;
    private int minimum;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date van;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(nullable=true)
    private Date tot;
    private OptieStatus status;
    private Integer volgorde;
    @OneToMany(mappedBy = "optieType", cascade= CascadeType.PERSIST)
    @Basic
    private List<Optie> opties = new ArrayList<Optie>(0);

    public OptieType() {
    }

    public OptieType(String naam, String omschrijving, int max, int min, Date van) {
        this.naam = naam;
        this.maximum = max;
        this.minimum = min;
        this.van = van;
        this.omschrijving = omschrijving;
        this.status = OptieStatus.HUIDIG;
    }

    public OptieType(String naam, String omschrijving, int max, int min, Date van, Date tot, OptieStatus status, Integer volgorde, List<Optie> opties) {
        this.naam = naam;
        this.maximum = max;
        this.minimum = min;
        this.van = van;
        this.tot = tot;
        this.status = status;
        this.volgorde = volgorde;
        this.opties = opties;
        this.omschrijving = omschrijving;
    }

    public void setKey(Key key) {
        this.key = key;
    }

    public Key getKey() {
        return key;
    }

    
    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    public String getOmschrijving() {
        return omschrijving;
    }

    public int getMax() {
        return this.maximum;
    }

    public void setMax(int max) {
        this.maximum = max;
    }

    public int getMin() {
        return this.minimum;
    }

    public void setMin(int min) {
        this.minimum = min;
    }

    public Date getVan() {
        return this.van;
    }

    public void setVan(Date van) {
        this.van = van;
    }

    public Date getTot() {
        return this.tot;
    }

    public void setTot(Date tot) {
        this.tot = tot;
    }

    public OptieStatus getStatus() {
        return this.status;
    }

    public void setStatus(OptieStatus status) {
        this.status = status;
    }

    public Integer getVolgorde() {
        return this.volgorde;
    }

    public void setVolgorde(Integer volgorde) {
        this.volgorde = volgorde;
    }

    public List<Optie> getOpties() {
        return this.opties;
    }

    public void setOpties(List<Optie> opties) {
        this.opties = opties;
    }

    @Override
    public String toString() {
        return "OPTIETYPE [" + id + ", " + naam + ", " + status + "]";
    }
    
    
}
