package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.enums.OptieStatus;
import domain.interfaces.Constrainable;
import domain.interfaces.Constrained;
import domain.interfaces.Constrainer;
import java.util.Date;
import javax.persistence.*;

/**
 * Optie generated by hbm2java
 */
@Entity
public class Optie implements java.io.Serializable, Constrainer, Constrainable, Constrained {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "OT_SEQUENCE")
    @SequenceGenerator(name = "OT_SEQUENCE")
    @Column(nullable=false)
    private Long id;
   @ManyToOne(cascade= CascadeType.PERSIST)
    private OptieType optieType;
    private String naam;
    private String omschrijving;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date van;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(nullable=true)
    private Date tot;
    private OptieStatus status;
    private Integer volgorde;
    
    public Optie() {
    }

    public Optie(OptieType optieType, String naam, String omschrijving, Date van, OptieStatus status, Integer volgorde) {
        this.optieType = optieType;
        this.status = status;
        this.volgorde = volgorde;
        this.naam = naam;
        this.van = van;
        this.omschrijving = omschrijving;
    }

    public Optie(OptieType optieType, String naam, String omschrijving, Date van, Date tot, OptieStatus status, Integer volgorde) {
        this.optieType = optieType;
        this.naam = naam;
        this.van = van;
        this.tot = tot;
        this.status = status;
        this.volgorde = volgorde;
        this.omschrijving = omschrijving;
    }

    public Key getKey() {
        return key;
    }

    public void setKey(Key key) {
        this.key = key;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public OptieType getOptieType() {
        return this.optieType;
    }

    public void setOptieType(OptieType optieType) {
        this.optieType = optieType;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    public String getOmschrijving() {
        return omschrijving;
    }

    public Date getVan() {
        return this.van;
    }

    public void setVan(Date van) {
        this.van = van;
    }

    public Date getTot() {
        return this.tot;
    }

    public void setTot(Date tot) {
        this.tot = tot;
    }

    public OptieStatus getStatus() {
        return this.status;
    }

    public void setStatus(OptieStatus status) {
        this.status = status;
    }

    public Integer getVolgorde() {
        return this.volgorde;
    }

    public void setVolgorde(Integer volgorde) {
        this.volgorde = volgorde;
    }

    @Override
    public String toString() {
        return "OPTIE [" + id + ", " + naam + ", " + optieType + ", " + status + ", " + van + "]";
    }

    
}
