package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.enums.Eenheid;
import domain.enums.PrijsType;
import domain.interfaces.Constrainable;
import domain.interfaces.Constrainer;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Entity;

/**
 * Prijs generated by hbm2java
 */
public class Prijs implements java.io.Serializable, Constrainable, Constrainer {

    private Long id;
    private PrijsKlasse prijsKlasse;
    private Conditie conditie;
    private Date van;
    private Date tot;
    private BigDecimal bedrag;
    private Eenheid eenheid;
    private PrijsType type;

    public Prijs() {
    }

    public Prijs(Long id, PrijsKlasse prijsKlasse, Date van, BigDecimal bedrag, Eenheid eenheid, PrijsType type) {
        this.id = id;
        this.prijsKlasse = prijsKlasse;
        this.van = van;
        this.bedrag = bedrag;
        this.eenheid = eenheid;
        this.type = type;
    }

    public Prijs(Long id, PrijsKlasse prijsKlasse, Conditie conditie, Date van, Date tot, BigDecimal bedrag, Eenheid eenheid, PrijsType type) {
        this.id = id;
        this.prijsKlasse = prijsKlasse;
        this.conditie = conditie;
        this.van = van;
        this.tot = tot;
        this.bedrag = bedrag;
        this.eenheid = eenheid;
        this.type = type;
    }

    public Key getKey() {
        return null;
    }
    
    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public PrijsKlasse getPrijsKlasse() {
        return this.prijsKlasse;
    }

    public void setPrijsKlasse(PrijsKlasse prijsKlasse) {
        this.prijsKlasse = prijsKlasse;
    }

    public Conditie getConditie() {
        return this.conditie;
    }

    public void setConditie(Conditie conditie) {
        this.conditie = conditie;
    }

    public Date getVan() {
        return this.van;
    }

    public void setVan(Date van) {
        this.van = van;
    }

    public Date getTot() {
        return this.tot;
    }

    public void setTot(Date tot) {
        this.tot = tot;
    }

    public BigDecimal getBedrag() {
        return this.bedrag;
    }

    public void setBedrag(BigDecimal bedrag) {
        this.bedrag = bedrag;
    }

    public Eenheid getEenheid() {
        return this.eenheid;
    }

    public void setEenheid(Eenheid eenheid) {
        this.eenheid = eenheid;
    }

    public PrijsType getType() {
        return this.type;
    }

    public void setType(PrijsType type) {
        this.type = type;
    }
}
