package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA

import com.google.appengine.api.datastore.Key;
import domain.enums.Eenheid;
import domain.enums.PrijsType;
import domain.interfaces.Constrainable;
import domain.interfaces.Constrainer;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import java.util.List;
import javax.persistence.*;
import utils.DateUtil;

/**
 * Prijs generated by hbm2java
 */
@Entity
public class Prijs implements java.io.Serializable, Constrainable, Constrainer {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Key key;
    @Basic(optional=false)
    @GeneratedValue(strategy= GenerationType.SEQUENCE, generator="P_SEQUENCE")
    @SequenceGenerator(name="P_SEQUENCE")
    private Long id;
    @ManyToOne
    private Conditie conditie;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date van;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(nullable=true)
    private Date tot;
    private BigDecimal bedrag;
    private Eenheid eenheid;
    private PrijsType type;

    public Prijs() {
    }

    public Prijs(Date van, BigDecimal bedrag, Eenheid eenheid, PrijsType type) {
        this.van = van;
        this.bedrag = bedrag;
        this.eenheid = eenheid;
        this.type = type;
    }

    public Prijs(Date van, BigDecimal bedrag, Eenheid eenheid, PrijsType type, Conditie conditie) {
        this.van = van;
        this.bedrag = bedrag;
        this.eenheid = eenheid;
        this.type = type;
        this.conditie = conditie;
    }
    
    /**
     * Create a Formule prijs without any conditions.
     * 
     * @param van
     * @param eenheid 
     */
    public Prijs(Date van, Eenheid eenheid) {
        this.van = van;
        this.eenheid = eenheid;
        this.type = PrijsType.FORMULE;
        this.bedrag = BigDecimal.ZERO;
    }
    
    /**
     * Create a Formule prijs with a condition.
     * 
     * @param van
     * @param eenheid 
     */
    public Prijs(Date van, Eenheid eenheid, Conditie conditie) {
        this.van = van;
        this.eenheid = eenheid;
        this.conditie = conditie;
        this.type = PrijsType.FORMULE;
        this.bedrag = BigDecimal.ZERO;
    }
    
    public Prijs(Conditie conditie, Date van, Date tot, BigDecimal bedrag, Eenheid eenheid, PrijsType type) {
        this.conditie = conditie;
        this.van = van;
        this.tot = tot;
        this.bedrag = bedrag;
        this.eenheid = eenheid;
        this.type = type;
    }
    
    public boolean hasFormule() {
        return type == PrijsType.FORMULE;
    }
    
    /**
     * Returns true if this prijs is applicable when the given opties are selected.
     * First it will check if there is a Conditie, if not, then the Prijs is applicable, 
     * otherwise, the conditie has to be met given the selected opties.
     * @param opties
     * @return 
     */
    public boolean isApplicable(List<Optie> opties) {
        Date today = DateUtil.today();
        
        return !today.before(van) 
                && (tot == null || !today.after(tot)) 
                &&((conditie == null) ? true : conditie.isApplicable(opties));
    }
    
    
    public Key getKey() {
        return key;
    }
    
    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Conditie getConditie() {
        return this.conditie;
    }

    public void setConditie(Conditie conditie) {
        this.conditie = conditie;
    }

    public Date getVan() {
        return this.van;
    }

    public void setVan(Date van) {
        this.van = van;
    }

    public Date getTot() {
        return this.tot;
    }

    public void setTot(Date tot) {
        this.tot = tot;
    }

    public BigDecimal getBedrag() {
        return this.bedrag.setScale(3, RoundingMode.HALF_UP);
    }

    public void setBedrag(BigDecimal bedrag) {
        this.bedrag = bedrag;
    }

    public Eenheid getEenheid() {
        return this.eenheid;
    }

    public void setEenheid(Eenheid eenheid) {
        this.eenheid = eenheid;
    }

    public PrijsType getType() {
        return this.type;
    }

    public void setType(PrijsType type) {
        this.type = type;
    }
    
    @Override
    public String toString() {
        return "PRIJS [" + id + ", " + bedrag + ", " + eenheid + ", " + type + ", " + van + ", " + conditie + "]";
    }   
}
