package domain;
// Generated 11-feb-2012 16:48:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrijsKlasse generated by hbm2java
 */
public class PrijsKlasse  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private Set<Prijs> prijzen = new HashSet<Prijs>(0);
     private Set<OpdrachtType> opdrachtTypes = new HashSet<OpdrachtType>(0);

    public PrijsKlasse() {
    }

	
    public PrijsKlasse(String naam) {
        this.naam = naam;
    }
    public PrijsKlasse(String naam, Set<Prijs> prijzen, Set<OpdrachtType> opdrachtTypes) {
       this.naam = naam;
       this.prijzen = prijzen;
       this.opdrachtTypes = opdrachtTypes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }

    public Set<Prijs> getPrijzen() {
        return this.prijzen;
    }
    
    public void setPrijzen(Set<Prijs> prijzen) {
        this.prijzen = prijzen;
    }

    public Set<OpdrachtType> getOpdrachtTypes() {
        return this.opdrachtTypes;
    }
    
    public void setOpdrachtTypes(Set<OpdrachtType> opdrachtTypes) {
        this.opdrachtTypes = opdrachtTypes;
    }




}


